### ISSUE TITLE
CloudFront generator doesn't recognize DefaultCacheBehavior.ForwardedValues

### ISSUE THREAD

**Issue by atramos** [iann0036/former2#126]
Here's the error:

```
Uncaught (in promise) TypeError: obj.data.DefaultCacheBehavior.ForwardedValues is undefined
    <anonymous> https://former2.com/js/services/cloudfront.js:552
    performF2Mappings https://former2.com/js/mappings.js:4378
    performF2Mappings https://former2.com/js/mappings.js:4376
    performF2Mappings https://former2.com/js/mappings.js:4362
    regenerateOutputs https://former2.com/js/app.js:876
    regenerateOutputs https://former2.com/js/app.js:875
    <anonymous> https://former2.com/js/app.js:869
    jQuery 2
        dispatch
        handle
```

**Comment by iann0036** [comment]
Hey @atramos,

Thanks for raising that one. Looks like there was some assumptions that fields were there, which weren't.

I've pushed a fix to hopefully resolve that bug. Let me know how that goes.

**Comment by egauk** [comment]
Still experiencing the issue:

`Uncaught (in promise) TypeError: obj.data.DefaultCacheBehavior.ForwardedValues is undefined
    <anonymous> https://former2.com/js/services/cloudfront.js:679
    performF2Mappings https://former2.com/js/mappings.js:4421
    performF2Mappings https://former2.com/js/mappings.js:4419
    performF2Mappings https://former2.com/js/mappings.js:4405
    regenerateOutputs https://former2.com/js/app.js:876
    regenerateOutputs https://former2.com/js/app.js:875
    <anonymous> https://former2.com/js/app.js:869
    jQuery 2
        dispatch
        handle`

**Comment by iann0036** [comment]
Thanks @egauk!

Looks like I missed some issues in my original fixes. Let me know if the latest update fixes those issues.

**Comment by egauk** [comment]
Confirmed resolved, thank you @iann0036!
